apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
    type: {{ .Values.service.type }}
    selector:
        app: demo-services
        #release: {{ .Release.Name }}
    ports:
        - name: demo-service-1-port
          protocol: TCP
          port: {{ .Values.service.port }}
          targetPort: {{ .Values.service.port }}
          #nodePort: 30036