replicaCount: 1

image:
    repository: rash11/deployment-demo
    tag: latest
    pullPolicy: Always

imagePullSecrets: []

serviceAccount:
    create: true
    annotations: {}
    Name: "demo-chart"
    
service:
    annotations: {}
    type: NodePort
    port: 8080

podAnnotations: {}

resources: {}

nodeSelector: {}

ingress:
    enabled: false

